#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
#  Aegis GRC Platform — One-Click Installer
#  Tested on: Ubuntu 22.04 / 24.04, Debian 12
#  Usage:  bash install.sh
# ═══════════════════════════════════════════════════════════════════
set -euo pipefail

# ── Colours ────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

log()  { echo -e "${GREEN}[✔]${NC} $*"; }
info() { echo -e "${CYAN}[→]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
err()  { echo -e "${RED}[✘]${NC} $*"; exit 1; }

# ── Banner ─────────────────────────────────────────────────────────
echo -e "${BOLD}${CYAN}"
echo "  ╔═══════════════════════════════════════╗"
echo "  ║        AEGIS GRC — INSTALLER          ║"
echo "  ║   Governance · Risk · Compliance      ║"
echo "  ╚═══════════════════════════════════════╝"
echo -e "${NC}"

# ── Root check ─────────────────────────────────────────────────────
[[ $EUID -ne 0 ]] && err "Run as root or with sudo:  sudo bash install.sh"

# ── Config ─────────────────────────────────────────────────────────
REPO_URL="https://github.com/xheavy0/Aegis_GRC_PLATFORM.git"
INSTALL_DIR="/opt/aegis-grc"
APP_PORT=80

echo ""
echo -e "${BOLD}Configuration${NC}"
echo "─────────────────────────────────────────"
read -rp "  Install directory  [${INSTALL_DIR}]: " in_dir
INSTALL_DIR="${in_dir:-$INSTALL_DIR}"

read -rp "  HTTP port          [${APP_PORT}]: " in_port
APP_PORT="${in_port:-$APP_PORT}"

read -rp "  Postgres password  [auto-generate]: " in_pg_pass
DB_PASS="${in_pg_pass:-$(openssl rand -hex 20)}"

read -rp "  Admin email        [admin@aegis.local]: " in_email
ADMIN_EMAIL="${in_email:-admin@aegis.local}"

read -rsp "  Admin password     [auto-generate]: " in_admin_pass; echo ""
ADMIN_PASS="${in_admin_pass:-$(openssl rand -hex 12)}"

SECRET_KEY=$(openssl rand -hex 32)
SERVER_IP=$(hostname -I | awk '{print $1}')

echo ""
echo -e "${BOLD}Summary${NC}"
echo "─────────────────────────────────────────"
echo "  Directory : ${INSTALL_DIR}"
echo "  Port      : ${APP_PORT}"
echo "  Admin     : ${ADMIN_EMAIL}"
echo "  Server IP : ${SERVER_IP}"
echo ""
read -rp "Proceed? [Y/n]: " yn
[[ "${yn,,}" == "n" ]] && echo "Aborted." && exit 0

# ── 1. System update ───────────────────────────────────────────────
info "Updating system packages..."
apt-get update -qq
apt-get install -y -qq curl git ca-certificates gnupg lsb-release openssl

# ── 2. Install Docker (official repo) ─────────────────────────────
if command -v docker &>/dev/null; then
    log "Docker already installed: $(docker --version)"
else
    info "Installing Docker..."
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/$(. /etc/os-release && echo "$ID")/gpg \
        | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/$(. /etc/os-release && echo "$ID") \
$(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    apt-get update -qq
    apt-get install -y -qq docker-ce docker-ce-cli containerd.io \
        docker-buildx-plugin docker-compose-plugin
    systemctl enable --now docker
    log "Docker installed: $(docker --version)"
fi

# ── 3. Clone / update repo ─────────────────────────────────────────
if [[ -d "${INSTALL_DIR}/.git" ]]; then
    info "Repository exists — pulling latest..."
    git -C "${INSTALL_DIR}" pull --ff-only
else
    info "Cloning repository..."
    git clone "${REPO_URL}" "${INSTALL_DIR}"
fi
log "Code ready at ${INSTALL_DIR}"

# ── 4. Write .env ──────────────────────────────────────────────────
info "Writing backend/.env ..."
cat > "${INSTALL_DIR}/backend/.env" <<EOF
# Auto-generated by install.sh on $(date)
DATABASE_URL=postgresql://aegis:${DB_PASS}@db:5432/aegis_grc
SECRET_KEY=${SECRET_KEY}
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=60
REFRESH_TOKEN_EXPIRE_DAYS=7
APP_ENV=production
DEBUG=false
APP_NAME=Aegis GRC Platform
APP_VERSION=1.0.0
CORS_ORIGINS=["http://${SERVER_IP}", "http://localhost"]
FIRST_ADMIN_EMAIL=${ADMIN_EMAIL}
FIRST_ADMIN_PASSWORD=${ADMIN_PASS}
FIRST_ADMIN_NAME=Administrator
EOF
chmod 600 "${INSTALL_DIR}/backend/.env"
log ".env written"

# ── 5. Write root .env for postgres password ───────────────────────
cat > "${INSTALL_DIR}/.env" <<EOF
POSTGRES_USER=aegis
POSTGRES_PASSWORD=${DB_PASS}
POSTGRES_DB=aegis_grc
EOF
chmod 600 "${INSTALL_DIR}/.env"

# ── 6. Update nginx port if custom ────────────────────────────────
if [[ "${APP_PORT}" != "80" ]]; then
    sed -i "s|\"80:80\"|\"${APP_PORT}:80\"|g" "${INSTALL_DIR}/docker-compose.yml"
fi

# ── 7. Pull images & start ─────────────────────────────────────────
info "Building and starting containers (this takes ~2-3 min first run)..."
cd "${INSTALL_DIR}"
docker compose pull --quiet 2>/dev/null || true
docker compose build --quiet
docker compose up -d
log "Containers started"

# ── 8. Wait for health ────────────────────────────────────────────
info "Waiting for API to become healthy..."
MAX=30; N=0
until docker compose exec -T api python -c \
    "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/health')" \
    &>/dev/null || [[ $N -ge $MAX ]]; do
    sleep 3; N=$((N+1))
    echo -n "."
done
echo ""

if [[ $N -ge $MAX ]]; then
    warn "API health check timed out. Check logs: docker compose -C ${INSTALL_DIR} logs api"
else
    log "API is healthy"
fi

# ── 9. Firewall (ufw) ──────────────────────────────────────────────
if command -v ufw &>/dev/null; then
    ufw allow "${APP_PORT}/tcp" &>/dev/null || true
    log "Firewall: port ${APP_PORT} opened"
fi

# ── 10. Done ───────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}═══════════════════════════════════════════${NC}"
echo -e "${BOLD}${GREEN}   ✅  Aegis GRC is live!${NC}"
echo -e "${BOLD}${GREEN}═══════════════════════════════════════════${NC}"
echo ""
echo -e "  🌐  URL:      ${BOLD}http://${SERVER_IP}:${APP_PORT}${NC}"
echo -e "  📧  Email:    ${BOLD}${ADMIN_EMAIL}${NC}"
echo -e "  🔑  Password: ${BOLD}${ADMIN_PASS}${NC}"
echo ""
echo -e "${YELLOW}  ⚠  Save your credentials — they won't be shown again!${NC}"
echo ""
echo -e "  Useful commands:"
echo -e "  ${CYAN}docker compose -C ${INSTALL_DIR} logs -f${NC}       # view logs"
echo -e "  ${CYAN}docker compose -C ${INSTALL_DIR} restart${NC}        # restart"
echo -e "  ${CYAN}docker compose -C ${INSTALL_DIR} down${NC}           # stop"
echo ""
